---
- hosts: controller
  remote_user: root
  gather_facts: False
  tasks:
  - name: install the python mysql
    yum:
      name: MySQL-python
      state: latest
  - name:
    mysql_db:
      login_user: "root"
      login_password: "123456"
      name: "keystone"
      state: "present"
    register: result
  - name:
    mysql_user:
      login_user: "root"
      login_password: "123456"
      name: "keystone"
      password: "keystone"
      host: "{{ item }}"
      state: "present"
      priv: "keystone.*:ALL"
    with_items:
       - "localhost"
       - "%"
  - name:
    yum:
      name: "{{ item }}"
    with_items:
       - openstack-keystone
       - httpd
       - mod_wsgi
  - lineinfile:
      dest: /etc/keystone/keystone.conf
      insertafter: '^\[database\]'
      line: 'connection = mysql+pymysql://keystone:keystone@controller/keystone'
  - lineinfile:
      dest: /etc/keystone/keystone.conf
      insertafter: '^\[token\]'
      line: 'provider = fernet'
  - command: "{{ item }}"
    with_items:
       - su -s /bin/sh -c "keystone-manage db_sync" keystone
       - keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
       - keystone-manage credential_setup --keystone-user keystone --keystone-group keystone
       - keystone-manage bootstrap --bootstrap-password admin --bootstrap-admin-url http://controller:35357/v3/ --bootstrap-internal-url http://controller:35357/v3/ --bootstrap-public-url http://controller:5000/v3/ --bootstrap-region-id RegionOne
  - name:
    lineinfile:
      dest: /etc/httpd/conf/httpd.conf
      insertafter: '^#ServerName'
      line: 'ServerName controller'
  - command: ln -s /usr/share/keystone/wsgi-keystone.conf /etc/httpd/conf.d/
    ignore_errors: True
  - command: systemctl enable httpd.service
  - name: restart httpd
    service:
      name: httpd
      state: started
  - copy:
      src: /playbook/config_file/env.sh
      dest: /env.sh
  - shell: "{{ item }}"
    with_items:
       - . /env.sh && openstack project create --domain default --description "Service Project" service
       - . /env.sh && openstack project create --domain default --description "Demo Project" demo
       - . /env.sh && openstack user create --domain default --password demo demo
       - . /env.sh && openstack role create user
       - . /env.sh && openstack role add --project demo --user demo user
       - . /env.sh && unset OS_AUTH_URL OS_PASSWORD
  - replace:
      dest: /etc/keystone/keystone-paste.ini
      regexp: ' admin_token_auth '
      replace: ' '
  - copy:
      src: /playbook/config_file/admin-openrc
      dest: /admin-openrc
  - copy:
      src: /playbook/config_file/demo-openrc
      dest: /demo-openrc
